; Automatically generated by Addon Management
#include *i %A_LineFile%\..\IC_Core\IC_Core_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
#include *i %A_LineFile%\..\IC_GameLocationSettings\IC_GameLocationSettings_Component.ahk
#include *i %A_LineFile%\..\IC_Theme_Manager\IC_Theme_Manager_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_CloseWelcomeBack\IC_BrivGemFarm_CloseWelcomeBack_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_AdvancedSettings\IC_BrivGemFarm_AdvancedSettings_Includes.ahk
#include *i %A_LineFile%\..\IC_Advanced_PresetRoutes\IC_Advanced_PresetRoutes_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Stats\IC_BrivGemFarm_Stats_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_LevelUp\IC_BrivGemFarm_LevelUp_Component.ahk
#include *i %A_LineFile%\..\IC_About\IC_About_Component.ahk
#include *i %A_LineFile%\..\IC_GameSettingsFix\IC_GameSettingsFix_Includes.ahk
#include *i %A_LineFile%\..\IC_ClaimDailyPlatinum\IC_ClaimDailyPlatinum_Includes.ahk
#include *i %A_LineFile%\..\IC_Oi_IC_CloseNow_ImWarningYou\IC_Oi_IC_CloseNow_ImWarningYou_Includes.ahk
